_commit: 271742c
_src_path: git@github.com:mizucopo/repo-template.git
author_email: mizu.copo@gmail.com
author_name: みず
docker_image_name: yt-thumb
docker_registry: mizucopo
project_dependencies: []
project_description: yt-thumb
project_name: yt-thumb
project_version: 0.1.0
python_version: '3.14'
use_aws_ecr: false
use_docker: true
use_gh_actions_docker_release: true
use_gh_actions_pr_tag_check: true
use_mit_license: true
use_python: true
